<?php
/** @package Taller::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("SeccionMap.php");

/**
 * SeccionDAO provides object-oriented access to the seccion table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Taller::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class SeccionDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $Nombre;

	/** @var string */
	public $Foto;

	/** @var int */
	public $Estatus;


	/**
	 * Returns a dataset of Producto objects with matching SeccionId
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetProductos($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "producto_ibfk_1", $criteria);
	}


}
?>