<?php
/** @package Taller::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("VentaMap.php");

/**
 * VentaDAO provides object-oriented access to the venta table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Taller::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class VentaDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var int */
	public $ProductoId;

	/** @var double */
	public $PrecioSugerido;

	/** @var double */
	public $PrecioFinal;

	/** @var int */
	public $CajaId;

	/** @var date */
	public $Fecha;

	/** @var string */
	public $Comentarios;

	/** @var int */
	public $Estatus;


	/**
	 * Returns the foreign object based on the value of CajaId
	 * @return Caja
	 */
	public function GetCaja()
	{
		return $this->_phreezer->GetManyToOne($this, "venta_ibfk_2");
	}

	/**
	 * Returns the foreign object based on the value of ProductoId
	 * @return Producto
	 */
	public function GetProducto()
	{
		return $this->_phreezer->GetManyToOne($this, "venta_ibfk_1");
	}


}
?>